name: Node.js Package

on:
  release:
    types: [created]
  pull_request:
  workflow_dispatch:

jobs:
  test-build-publish:
    name: Test, Build, and Publish Node.js Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies (Cache hit will skip actual installation)
        run: |
          bun install
      - name: Run tests
        run: |
          bun test
      - name: Build package
        run: |
          bun run build
      - name: Publish package
        # only run this step if it's a release or a manual trigger
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: |
          bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
